/*
 * Generated by src/saveVersion.sh
 */
@HadoopVersionAnnotation(version="1.0.4-SNAPSHOT", revision="", 
                         user="root", date="Sun Dec 30 01:29:55 PST 2012", url="",
                         srcChecksum="01fa6e404ebd055f0296be515f74a99b")
package org.apache.hadoop;
